"""
Script para crear el schema de pruebas test_python en SAP HANA.

⚠️ ADVERTENCIA: Este script crea objetos en SAP HANA.
   Solo ejecutar en ambiente de desarrollo o con autorización.
"""
import sys
import os

# Agregar el directorio padre al path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from hana import (
    get_hana_connection,
    schema_exists,
    table_exists,
    create_table,
    drop_table,
    execute_ddl,
    user_exists,
    create_user
)


def setup_test_python_schema():
    """Crea y configura el schema test_python para pruebas en SAP HANA."""
    print("=" * 80)
    print("CONFIGURACIÓN DE SCHEMA DE PRUEBAS: test_python (SAP HANA)")
    print("=" * 80)
    print("\n⚠️  ADVERTENCIA: Este script modificará SAP HANA")
    print("   Solo ejecutar en ambiente de desarrollo\n")

    schema_name = 'TEST_PYTHON'

    # Confirmar ejecución
    response = input("¿Desea continuar? (s/n): ")
    if response.lower() != 's':
        print("Operación cancelada por el usuario")
        return False

    try:
        # 1. Verificar si el schema existe
        print(f"\n1. Verificando si existe el schema '{schema_name}'...")
        if schema_exists(schema_name):
            print(f"   El schema '{schema_name}' ya existe.")
            response = input("   ¿Desea recrearlo? (s/n): ")
            if response.lower() == 's':
                print(f"   Eliminando schema '{schema_name}'...")
                # En HANA, eliminar schema también elimina todos sus objetos
                execute_ddl(f"DROP SCHEMA {schema_name} CASCADE")
                print("   ✓ Schema eliminado")
            else:
                print("   Manteniendo schema existente")
                # Continuar con la creación de tablas si no existen

        # 2. Crear schema si no existe
        if not schema_exists(schema_name):
            print(f"\n2. Creando schema '{schema_name}'...")
            execute_ddl(f"CREATE SCHEMA {schema_name}")
            print("   ✓ Schema creado exitosamente")

        # 3. Crear tablas de ejemplo
        print("\n3. Creando tablas de ejemplo...")

        # Tabla: TEST_CLIENTES
        if not table_exists('TEST_CLIENTES', schema=schema_name):
            print("   Creando tabla 'TEST_CLIENTES'...")
            create_table(
                'TEST_CLIENTES',
                {
                    'ID': 'INTEGER GENERATED BY DEFAULT AS IDENTITY',
                    'NOMBRE': 'NVARCHAR(100) NOT NULL',
                    'EMAIL': 'NVARCHAR(100)',
                    'TELEFONO': 'NVARCHAR(20)',
                    'ACTIVO': 'TINYINT DEFAULT 1',
                    'FECHA_REGISTRO': 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP'
                },
                primary_key='ID',
                table_type='COLUMN',  # COLUMN store para mejor rendimiento
                schema=schema_name
            )
            print("   ✓ Tabla 'TEST_CLIENTES' creada")

        # Tabla: TEST_PRODUCTOS
        if not table_exists('TEST_PRODUCTOS', schema=schema_name):
            print("   Creando tabla 'TEST_PRODUCTOS'...")
            create_table(
                'TEST_PRODUCTOS',
                {
                    'ID': 'INTEGER GENERATED BY DEFAULT AS IDENTITY',
                    'CODIGO': 'NVARCHAR(50) NOT NULL',
                    'NOMBRE': 'NVARCHAR(100)',
                    'DESCRIPCION': 'NCLOB',
                    'PRECIO': 'DECIMAL(18,2)',
                    'STOCK': 'INTEGER DEFAULT 0',
                    'ACTIVO': 'TINYINT DEFAULT 1',
                    'FECHA_CREACION': 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP'
                },
                primary_key='ID',
                table_type='COLUMN',
                schema=schema_name
            )
            print("   ✓ Tabla 'TEST_PRODUCTOS' creada")

        # Tabla: TEST_VENTAS
        if not table_exists('TEST_VENTAS', schema=schema_name):
            print("   Creando tabla 'TEST_VENTAS'...")
            create_table(
                'TEST_VENTAS',
                {
                    'ID': 'INTEGER GENERATED BY DEFAULT AS IDENTITY',
                    'CLIENTE_ID': 'INTEGER',
                    'PRODUCTO_ID': 'INTEGER',
                    'CANTIDAD': 'INTEGER NOT NULL',
                    'PRECIO_UNITARIO': 'DECIMAL(18,2)',
                    'TOTAL': 'DECIMAL(18,2)',
                    'FECHA_VENTA': 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP'
                },
                primary_key='ID',
                table_type='COLUMN',
                schema=schema_name
            )
            print("   ✓ Tabla 'TEST_VENTAS' creada")

        # 4. Crear usuario de prueba (opcional)
        print("\n4. ¿Desea crear un usuario de prueba?")
        response = input("   (s/n): ")
        if response.lower() == 's':
            test_user = 'TEST_USER'
            if not user_exists(test_user):
                print(f"   Creando usuario '{test_user}'...")
                create_user(test_user, 'TestPass123!')
                print(f"   ✓ Usuario '{test_user}' creado")

                # Otorgar permisos
                from hana import grant_permission
                print(f"   Otorgando permisos al usuario...")
                grant_permission('SELECT', user_name=test_user, schema=schema_name)
                grant_permission('INSERT', user_name=test_user, schema=schema_name)
                grant_permission('UPDATE', user_name=test_user, schema=schema_name)
                grant_permission('DELETE', user_name=test_user, schema=schema_name)
                print(f"   ✓ Permisos otorgados")
            else:
                print(f"   El usuario '{test_user}' ya existe")

        print("\n" + "=" * 80)
        print(f"✓ SCHEMA '{schema_name}' CONFIGURADO EXITOSAMENTE")
        print("=" * 80)
        print("\nTablas creadas (COLUMN store):")
        print("  - TEST_CLIENTES   (para pruebas de clientes)")
        print("  - TEST_PRODUCTOS  (para pruebas de productos)")
        print("  - TEST_VENTAS     (para pruebas de ventas)")
        print("\nConexión:")
        print(f"  Schema: {schema_name}")
        print(f"  Tablas: 3")
        print("\nEjemplo de uso:")
        print("  from paquetes.hana import *")
        print(f"  select('TEST_CLIENTES', schema='{schema_name}')")
        print("=" * 80 + "\n")

        return True

    except Exception as e:
        print(f"\n❌ Error configurando el schema: {e}")
        import traceback
        traceback.print_exc()
        return False


def show_schema_info():
    """Muestra información del schema test_python."""
    schema_name = 'TEST_PYTHON'

    print("\n" + "=" * 80)
    print(f"INFORMACIÓN DEL SCHEMA: {schema_name} (SAP HANA)")
    print("=" * 80)

    try:
        if not schema_exists(schema_name):
            print(f"\n❌ El schema '{schema_name}' no existe.")
            print("   Ejecuta este script para crearlo.")
            return

        from hana import execute_query, get_table_columns

        # Listar tablas
        tables = execute_query("""
            SELECT TABLE_NAME, TABLE_TYPE, RECORD_COUNT
            FROM SYS.TABLES
            WHERE SCHEMA_NAME = ?
            ORDER BY TABLE_NAME
        """, params=(schema_name,))

        print(f"\nTablas en '{schema_name}':")
        for table in tables:
            table_name = table[0]
            table_type = table[1]
            record_count = table[2]

            print(f"\n  📊 {table_name} ({table_type}) - {record_count} registros")

            # Mostrar columnas de cada tabla
            columns = get_table_columns(table_name, schema=schema_name)
            print(f"     Columnas ({len(columns)}):")
            for col in columns:
                nullable = "NULL" if col['is_nullable'] else "NOT NULL"
                length_info = f"({col['length']})" if col['length'] else ""
                print(f"       • {col['name']}: {col['type']}{length_info} {nullable}")

        # Información del schema
        print(f"\n📈 Estadísticas del schema:")
        schema_info = execute_query("""
            SELECT
                COUNT(*) as total_tables,
                SUM(RECORD_COUNT) as total_records,
                SUM(MEMORY_SIZE_IN_TOTAL) / 1024 / 1024 as size_mb
            FROM SYS.M_TABLES
            WHERE SCHEMA_NAME = ?
        """, params=(schema_name,))

        if schema_info and schema_info[0]:
            info = schema_info[0]
            print(f"   Total de tablas: {info[0]}")
            print(f"   Total de registros: {info[1] or 0}")
            print(f"   Tamaño en memoria: {info[2] or 0:.2f} MB")

        print("\n" + "=" * 80 + "\n")

    except Exception as e:
        print(f"\n❌ Error obteniendo información: {e}")
        import traceback
        traceback.print_exc()


def drop_test_schema():
    """Elimina el schema de pruebas test_python."""
    schema_name = 'TEST_PYTHON'

    print("\n" + "=" * 80)
    print(f"ELIMINAR SCHEMA: {schema_name}")
    print("=" * 80)
    print("\n⚠️  ADVERTENCIA: Esta operación eliminará el schema y TODOS sus objetos")
    print(f"   Schema a eliminar: {schema_name}\n")

    # Confirmar
    response = input("¿Está seguro que desea eliminar el schema? (escriba 'CONFIRMAR'): ")
    if response != 'CONFIRMAR':
        print("Operación cancelada")
        return False

    try:
        if not schema_exists(schema_name):
            print(f"\n❌ El schema '{schema_name}' no existe.")
            return False

        print(f"\nEliminando schema '{schema_name}'...")
        execute_ddl(f"DROP SCHEMA {schema_name} CASCADE")
        print(f"✓ Schema '{schema_name}' eliminado exitosamente")

        return True

    except Exception as e:
        print(f"\n❌ Error eliminando schema: {e}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        if sys.argv[1] == 'info':
            # Modo información
            show_schema_info()
        elif sys.argv[1] == 'drop':
            # Modo eliminación
            drop_test_schema()
        else:
            print("Uso:")
            print("  python setup_test_schema.py        - Crear/configurar schema")
            print("  python setup_test_schema.py info   - Ver información del schema")
            print("  python setup_test_schema.py drop   - Eliminar schema")
    else:
        # Modo setup
        if setup_test_python_schema():
            print("\n✓ Configuración completada")
            show_schema_info()
            sys.exit(0)
        else:
            sys.exit(1)
